version: '3.2' # specify docker-compose version


volumes:
  app:


# Define the services/containers to be run
services:
  python:
    build:
      context: . # We set this context to load the app requirements when building the image
      dockerfile: ./Dockerfile # uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - type: volume
        source: app
        target: /code/app
    ports:
      - "8000:8000"
    
  nginx:
    image: nginx
    volumes:
      - type: volume
        source: app
        target: /var/www/public/
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/html/404.html:/usr/share/nginx/html/404.html"
      - "~/cert/rover:/etc/ssl"
    ports:
      - "80:80"
      - "443:443"
    expose: 
      - "80"
    depends_on:
      - python

